# Generated by Django 2.2.4 on 2019-09-19 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('source_url', models.URLField(verbose_name='URL to origin video in s3')),
                ('source_thumbnail', models.URLField(blank=True, verbose_name='URL to video thumbnail')),
                ('source_size_in_kb', models.IntegerField(verbose_name='video size in kilobytes')),
                ('duration_in_seconds', models.IntegerField(blank=True, verbose_name='duration in seconds')),
                ('stream_url', models.URLField(blank=True, verbose_name='URL to converted stream video')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
