# Generated by Django 2.2.4 on 2019-09-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_size_in_kb',
            field=models.IntegerField(blank=True, verbose_name='video size in kilobytes'),
        ),
    ]
