# Generated by Django 2.2.4 on 2019-09-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190919_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_in_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_size_in_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='video size in kilobytes'),
        ),
    ]
