# Generated by Django 2.2.4 on 2019-09-19 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190919_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
